In [1]:
import pandas as pd
import numpy as np

In [2]:
import json

In [3]:
df = pd.read_json('result.json')
df1 = df[df['title'].notna()]
df1.reset_index(inplace = True)

In [4]:
df2=df1['personal_rating']
df2[35]=[]
df2[39]=[]
df2[114]=[]
df2[241]=[]


<ipython-input-4-8d82de260327>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[35]=[]
C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-4-8d82de260327>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[39]=[]
<ipython-input-4-8d82de260327>:4: SettingWithCopyWarning: 
A value is trying to be

In [5]:
a=[]
for i in range(0,len(df2)):
    for j in range(0,len(df2[i])):
        a.append(df2[i][j][0])
a=pd.DataFrame(a)
b=a.drop_duplicates()

In [6]:
b=b.values.tolist()

In [7]:
print(b)

[['rhaeredekop from Winnipeg, MB '], ['lizgoldsmith1960 from Lincoln, MA '], ['bmaybeegeorge from Canada'], ['adventurousz from Boulder, CO '], ['epaul77 from Mississippi '], ['lizzydlangley from St. Louis '], ['Jweyant from Maine '], ['tjsnuffin from Cincinnati, OH '], ['sarahglittle7930 from Denver, CO '], ['wendymochi from Torrance '], ['ayydre from California '], ['susanweiss from Rockville, MD '], ['silvia_v from Belmont, MA '], ['Tejanacooks from Texas '], ['kevinj308 '], ['cellocath85 from Maryland '], ['mvross from Texas '], ['lhdowney from Charlotte, NC '], ['jsbjk from Winnetka, IL '], ['karen8221 from Westchester County, NY '], ['idesalos from Houston '], ['colettestp from Montreal, Canada '], ['yoshihaga22 from Laguna Beach, Ca. '], ['anniemh5 '], ['diana.kulpa1463 from Toronto, ON '], ['ilyssa2 from NY, NY '], ['dory92064 from San Diego, CA '], ['travel80 from Winnipeg, MB '], ['amyhenriott '], ['mhaas12 from Philadelphia, PA '], ['mtnmeye '], ['greenstein.rebecca9820 from

In [8]:
M=np.zeros((len(b),len(df2)))
gp3=-1
for i in range(0,len(df2)):
    for j in range(0,len(df2[i])):
        for t in range(len(b)):
            if(df2[i][j][0]==b[t][0]):
                gp3=t
        M[gp3][i]=df2[i][j][1]
        gp3=-1
                 

In [9]:
print(M)
M.shape

[[5. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 5.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 4.]]


(2884, 289)

In [10]:
#insert rating of team members
M1=np.zeros((2888,289))
for i in range(2884):
    for j in range(289):
         M1[i][j]=M[i][j]
Yu=[19,107,207,56,14,67,130,31]
Yu1=[3,1,4,4,3,3,2,5]
Pt=[10,21,210,240,170,150,190,280]
Pt1=[4,3,5,2,3,4,2,3]
Rx=[27,39,78,83,97,127,136,149]
Rx1=[4,5,2,1,2,5,4,5]
Ll=[85,4,156,257,121,134,238,133]
Ll1=[5,5,4,3,3,2,1,2]
M1[2884,Yu]=Yu1
M1[2885,Pt]=Pt1
M1[2886,Rx]=Rx1
M1[2887,Ll]=Ll1
M=M1
M
M.shape

array([[5., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
#for user i, the dishes index that has been rated
def get_d(M,i):
    dishes=[]
    for j in range(0,289):
        if(M[i][j]>0):
            dishes.append(j)
    return dishes
        

In [12]:
#for dishes j, the users index that has rated the dishes
def get_u(M,j):
    user=[]
    for i in range(0,2888):
        if(M[i][j]>0):
            user.append(i)
    return user

In [13]:
def sum_v(i,v):
    result=0
    dishes=get_d(M,i)
    for p in dishes:
        result=result+np.dot(v[p],v[p].T)
    return result 

In [14]:
def sum_u(j,u):
    result=0
    user=get_u(M,j)
    for p in user:
        result=result+np.dot(u[p],u[p].T)
    return result

In [15]:
def sum_Mv(i,v):
    result=0
    dishes=get_d(M,i)
    for p in dishes:
        result=result+M[i][p]*v[p]
    return result

In [16]:
def sum_Mu(j,u):
    result=0
    user=get_u(M,j)
    for p in user:
        result=result+M[p][j]*u[p]
    return result

In [17]:
v=np.zeros((10,289))
for i in range(10):
    v[i]=np.random.normal(0,0.5,289)
v=v.T #10*289->289*10
u=np.zeros((2888,10))
for t in range(200):
    for i in range(2888):
        u[i]=(1/(2*1+sum_v(i,v)))*(sum_Mv(i,v))
    for j in range(289):
        v[j]=(1/(2*1+sum_u(j,u)))*(sum_Mu(j,u))
    print(t)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199


In [18]:
MP=np.dot(u,v.T)
MP=np.around(MP)

[ 4.  3.  3.  3.  3.  4.  4.  0. -1.  3.  4.  5.  2.  3.  4.  3. -0.  5.
  4.  3.  4.  4. -2. -1.  4.  3.  4.  4. -1. -1.  1.  1.  5.  5.  3.  0.
  0. -1. -0.  2.  4.  5.  1.  4.  4.  1.  0.  5.  5.  1.  4. -1. -0. -1.
  4.  1.  3. -1.  4.  4.  3.  3.  0.  5.  1.  1.  5.  4.  4.  1.  0. -1.
 -0.  3.  4.  4.  4.  0.  3.  1.  3.  3.  0.  2. -1.  5.  5.  0.  3.  0.
  0.  4. -2. -1.  4.  4.  4.  4.  0.  4.  4.  1. -2. -1.  4.  0.  4.  1.
  5.  2.  4. -1.  3.  0.  0.  5.  4.  4.  5.  0.  0.  4.  4.  5.  1.  4.
  3.  4.  3.  1.  2.  0.  3.  3.  3.  4.  3.  0. -0.  4.  2.  3.  4. -1.
  5.  5.  3.  5.  0.  2.  5.  1. -0.  0.  1. -1.  2. -2.  3. -0.  4.  0.
  4.  4.  0.  3. -3.  0. -1.  4.  2.  3.  5.  4. -2.  0. -1.  1.  4.  0.
  3.  5.  1.  5.  4.  4.  4.  5.  0.  4.  2.  1.  1.  1.  5.  1. -0.  3.
  0.  4.  3.  3.  0.  5.  4.  0.  5.  3.  4. -0.  4.  4.  3.  5.  4.  5.
 -0.  1.  5. -1.  3. -0.  1. -1.  0.  3.  4.  0.  0.  0.  5.  5.  4.  0.
  2.  3.  2. -1.  3.  3.  4.  0.  0.  1.  0.  4.  4

In [19]:
i=[4,85,90,134,156,133,121,238,257]
df1['title'][i]

4      Grain Salad with Olives and Whole-Lemon Vinaig...
85                   Broiled Cod with Fennel and Orange 
90          Haitian Beef and Pumpkin Soup (Soup Joumou) 
134           Ricotta-Pumpkin Gnocchi with Brown Butter 
156          Wine-Braised Brisket With Butternut Squash 
133             Sheet-Pan Roasted Squash and Feta Salad 
121                           The Winterized Penicillin 
238                                    Herbed Chickpeas 
257       Spanish Frittata with Herby Yogurt and Greens 
Name: title, dtype: object

In [20]:
print(np.matrix(MP))

[[ 5.  3.  4. ...  4. -0.  1.]
 [ 5.  3.  4. ...  4. -0.  1.]
 [ 5.  3.  4. ...  4. -0.  1.]
 ...
 [ 4.  3.  3. ...  4. -0.  0.]
 [ 4.  3.  3. ...  4. -0.  1.]
 [ 4.  3.  3. ...  4. -0.  1.]]


In [21]:
MP=MP.T
MP=pd.DataFrame(MP)
MP=pd.DataFrame.drop(MP,index=
[18,
 22,
 24,
 30,
 33,
 51,
 53,
 58,
 61,
 72,
 73,
 77,
 79,
 87,
 89,
 105,
 125,
 128,
 139,
 149,
 162,
 163,
 168,
 186,
 211,
 213,
 221,
 230,
 233,
 265,
 270,
 272,
 285])
MP=MP.reset_index(drop=True)

In [22]:
MP=MP.values
MP=MP.T

In [23]:
df2 = df.dropna(subset=['title','calories','sodium','fat','protein'])
df2.reset_index(inplace = True)

In [24]:
df2

index                                              title  rating  \
0        0          Curried Lentil, Tomato, and Coconut Soup      5.0   
1        1  Roasted Butternut Squash with Herb Oil and Goa...     4.5   
2        2                                   Pumpkin Muffins      4.0   
3        3  Chopped Salad with Shallot Vinaigrette, Feta, ...     5.0   
4        4  Grain Salad with Olives and Whole-Lemon Vinaig...     3.5   
..     ...                                                ...     ...   
251    292                               White Chicken Chili      5.0   
252    293  One-Pot Curried Cauliflower with Couscous and ...     4.5   
253    295  Hummus Dinner Bowls with Spiced Ground Beef an...     4.5   
254    296                                 Autumn Kale Salad      5.0   
255    297       Pumpkin Icebox Pie With Snickerdoodle Crust      4.5   

     calories  sodium    fat  protein  \
0       437.0   667.0   28.0     13.0   
1       175.0   576.0    9.0      4.0   
2       364.0   183.0   11.0      6.0   
3       170.0   413.0   13.0      6.0   
4       330.0   483.0   19.0      8.0   
..        ...     ...    ...      ...   
251     534.0   968.0   14.0     45.0   
252     606.0  1365.0   15.0     27.0   
253     329.0   327.0   26.0     20.0   
254     287.0   329.0   22.0      4.0   
255    3597.0  1869.0  223.0     33.0   

                                       personal_rating  
0    [[rhaeredekop from Winnipeg, MB , 5], [lizgold...  
1    [[ilyssa2 from NY, NY , 5], [dory92064 from Sa...  
2    [[mtnmeye , 3], [greenstein.rebecca9820 from N...  
3    [[brushjl from solon, oh , 5], [tatyana_poirie...  
4    [[auntwebbie from Allen, TX , 5], [krf from Be...  
..                                                 ...  
251  [[lmanderson from Maryland , 5], [debkane from...  
252  [[mkopke from Toronto, Canada , 4], [akraemer1...  
253  [[bradley2 from Foodietown, ,PA , 4], [chaurie...  
254  [[dottie60 from Boston , 5], [zeta from Victor...  
255  [[Lois33 from EGR, Michigan , 5], [mccoyj25 fr...  

[256 rows x 8 columns]

In [31]:
print(MP)
MP.shape

[[ 5.  3.  4. ...  4. -0.  1.]
 [ 5.  3.  4. ...  4. -0.  1.]
 [ 5.  3.  4. ...  4. -0.  1.]
 ...
 [ 4.  3.  3. ...  4. -0.  0.]
 [ 4.  3.  3. ...  4. -0.  1.]
 [ 4.  3.  3. ...  4. -0.  1.]]


(2888, 256)

In [25]:
#np.savetxt('pj2.csv',MP)
#sodium=df2['sodium']
#np.savetxt('sodium.csv',sodium)
#fat=df2['fat']
#np.savetxt('fat.csv',fat)
#protein=df2['protein']
#np.savetxt('protein.csv',protein)

In [26]:
calories=df2['calories']
#np.savetxt('calories.csv',calories)